let name = "Pepito";
let surname = "Gargollo";
let student = `${name} ${surname}`;
let studentMayus = student.toUpperCase();
let studentMinus = student.toLowerCase();
let numbLetters = student.length
let initialName = name[0];
let lastSurname = surname[surname.length - 1];
let withoutSpaces = student.replace(" ", "");
let contentName = student.includes(name);
